name: Docker

on:
  workflow_dispatch:
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "::group::My title"
            cat /proc/cpuinfo
